name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build
      
      # macOS 单独打 Mac 包
      - name: Build Mac Releases
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.os == 'macos-latest'
        run: npm exec electron-builder -- --publish always --mac

      # Windows 单独打 Windows 包
      - name: Build Windows Releases
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.os == 'windows-latest'
        run: npm exec electron-builder -- --publish always --win