name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - run: |
          npm install
          npm run postinstall
          npm run build

      # macOS
      - name: Build Mac
        if: matrix.os == 'macos-latest'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm exec electron-builder -- --publish always --mac

      # Windows
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: npm exec electron-builder -- --win
